### NumPy Indexing and Selection

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [15]:
arr[0:5] = 100
# This will broadcast the value to first 5 digits to be 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [24]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Important note on slices of array

In [25]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [26]:
# braoadcasting on "slice_of_arr"
# Slice of an array is just a view. Any changes made to that slice will actually change the values in array.
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [27]:
# values in arr
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
# To avoid the above problem, use copy method of array to copy the values to another array.
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


In [30]:
# Broadcasted to a slice in arr_copy with value 100. But it will not effect the values of actual array.
arr_copy[0:6] = 100
print(arr_copy)

[100 100 100 100 100 100   6   7   8   9  10]


In [31]:
# Checking values in arr
print(arr)

[99 99 99 99 99 99  6  7  8  9 10]


# Indexing a 2d array

In [43]:
# Converting a nested list into an array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

##### Grabing elements using 'Double bracket' format

In [34]:
print(arr_2d[0][0],arr_2d[0][1],arr_2d[0][2],arr_2d[1][0],arr_2d[1][1],arr_2d[1][2])
print(arr_2d[2][0],arr_2d[2][1],arr_2d[2][2])

5 10 15 20 25 30
35 40 45


#### Grabing elements usign "Single bracket format"

In [35]:
print(arr_2d[0,0],arr_2d[0,1],arr_2d[0,2],arr_2d[1,0],arr_2d[1,1],arr_2d[1,2],arr_2d[2,0],arr_2d[2,1],arr_2d[2,2])

5 10 15 20 25 30 35 40 45


#### To get submatrices from a matrix do slicing on Single bracket format

In [45]:
# To get top right corner of arr_2d array
# Here it drops the first column.
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [46]:
# Selects every column of first and second row
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [50]:
# difference between arr_2d[1:2] and arr_2d[1]
print(arr_2d[1:2])
print(arr_2d[1])
print(arr_2d[1:2,:])
print(arr_2d[1:2][0])

[[20 25 30]]
[20 25 30]
[[20 25 30]]
[20 25 30]


In [55]:
# What is the difference?
print(arr_2d[:,1],arr_2d[:,1:2],sep='\n')

[10 25 40]
[[10]
 [25]
 [40]]


#### Conditional Selection

In [58]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
# Compare the array arr with comparision operator to get a full boolean array.
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [60]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
# Using boolean array bool_arr to actually index or conditionally select elements from original array
arr[bool_arr]
# It only returns the instances where the boolean array is true.

array([ 6,  7,  8,  9, 10])

In [62]:
# To get all the elements of array less than 3
arr[arr<3]

array([1, 2])

In [63]:
arr_2d = np.arange(50).reshape(5,10)

In [64]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [66]:
# To grab [[13,14],[23,24]]
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [71]:
print(arr_2d[1,2],arr_2d[1:3][1],arr_2d[1:3,1],arr_2d[1:3,1:5],sep='\n')

12
[20 21 22 23 24 25 26 27 28 29]
[11 21]
[[11 12 13 14]
 [21 22 23 24]]
