# Python numpy arrays
# casting lists into numpy arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)
print(arr)

[1 2 3]


In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Creating a numpy array

In [12]:
np.arange(start=3,stop=10,step=0.5,dtype=int)
# for floating point value in step length = ceil((stop-start)/step)
# actual step = dtype(start+step)-dtype(start)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [13]:
np.arange(start=3,stop=10,step=0.5,dtype=float)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

# To generate array of zeros

In [22]:
print(np.zeros((2,3),int),np.zeros((1,)),np.zeros(4),sep='\n')

[[0 0 0]
 [0 0 0]]
[0.]
[0. 0. 0. 0.]


# To generate array of ones

In [21]:
print(np.ones((3,2),dtype=int))

[[1 1]
 [1 1]
 [1 1]]


# np.linespace() to get evenely spaced elements from start to stop

In [23]:
np.linspace(0,6,10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

# To generate Identity matrix

In [27]:
np.eye(N=5,M=5,k=0,dtype=int,)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Creating arrays of random numbers

In [29]:
print(np.random.rand(),np.random.rand(3),np.random.rand(4,5),sep='\n')

0.610239677462221
[0.15191407 0.72445121 0.17107371]
[[0.60843622 0.76848644 0.17115707 0.03459579 0.95547205]
 [0.35561343 0.95740876 0.78060352 0.28624242 0.83986829]
 [0.89595981 0.61954301 0.41977606 0.50588425 0.44655292]
 [0.33890395 0.19707273 0.24659288 0.53642446 0.59015366]]


In [36]:
print(np.random.randn(2,3),2+3*np.random.randn(2,2),sep='\n')

[[-0.44388098 -0.34145051 -1.37290091]
 [ 0.03778907 -1.64276579  1.27428037]]
[[-0.95700903  1.33997899]
 [ 4.78598678  1.35179943]]


# To generate random integers in an interval

In [40]:
print(np.random.randint(1,100,size=7),np.random.randint(4,size=(3,5)),np.random.randint(low=4,high=None,size=(2,3)),sep='\n')

[65 57 38  3 50 67 29]
[[2 2 2 1 0]
 [1 3 3 1 3]
 [2 3 2 3 0]]
[[1 2 1]
 [1 3 0]]


In [42]:
ranarr = np.random.randint(0,50,10)

In [43]:
arr = np.arange(25)

In [48]:
print(arr.reshape(5,5),ranarr.reshape(2,5),sep='\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 2 36 14 27 11]
 [13  6  5 29  9]]


# To get maximum and minimum values

In [52]:
print(arr.max(),ranarr.max(),ranarr.min())

24 36 2


# To get index values of maximum and minimum values

In [54]:
print(ranarr.argmax(),ranarr.argmin())

1 0


In [58]:
# To get shape of array
print(arr.reshape(5,5).shape,ranarr.shape)
# To get data type of array
print(arr.dtype)

(5, 5) (10,)
int32
